//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
namespace BusinessLayerLibrary.Domain.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Offer
    {
        [Key]
        public int IdOffer { get; set; }

        public int IdUser { get; set; }

        [Required]
        [StringLength(100)]
        public string NameOffer { get; set; }

        [Required]
        [StringLength(150)]
        public string Description { get; set; }

        [Column(TypeName = "date")]
        public DateTime Date { get; set; }

        public short Type { get; set; }

        [StringLength(20)]
        public string State { get; set; }

        public virtual User User { get; set; }
    }
}
